package hk.ust;

import hk.ust.aggregate.Q10Aggregator;
import hk.ust.aggregate.TopKMaintainer;
import hk.ust.aju.JoinResult;
import hk.ust.aju.Q10ProcessFunction;
import hk.ust.model.TupleUpdate;
import hk.ust.model.TupleUpdate.*;
import hk.ust.model.UpdateType;
import hk.ust.sink.DeltaSink;
import hk.ust.source.TpchCsvParser;
import java.io.BufferedReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import org.apache.flink.api.common.typeinfo.TypeInformation;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;

/**
 * AJU (Acyclic Join under Updates) streaming job for TPC-H Q10.
 *
 * <p>Implements the algorithm from: Qichen Wang, Ke Yi. "Maintaining Acyclic Foreign-Key Joins
 * under Updates." SIGMOD 2020.
 *
 * <p>Pipeline: Source -> Q10ProcessFunction -> Q10Aggregator -> TopKMaintainer -> DeltaSink
 *
 * <p>The Q10ProcessFunction is the core AJU algorithm that incrementally maintains the 4-way join
 * result. It emits per-lineitem join deltas which are then aggregated into per-customer revenue
 * sums and filtered to top-20.
 */
public class AjuStreamJob {

  public static void main(String[] args) throws Exception {
    StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

    // Single-partition mode: all state co-located for the chain join.
    // This matches the paper's single-thread evaluation mode.
    env.setParallelism(1);

    // =====================================================================
    // Resolve TPC-H data directory from environment
    // =====================================================================

    String tpchDataDir = System.getenv("TPCH_DATA_DIR");
    if (tpchDataDir == null || tpchDataDir.trim().isEmpty()) {
      throw new IllegalStateException(
          "TPCH_DATA_DIR environment variable is not set. "
              + "Point it to the directory containing .tbl files generated by dbgen.");
    }

    // =====================================================================
    // Pre-load all updates from .tbl files in bottom-up order.
    // Bottom-up (nation, customer, orders, lineitem) ensures that when a
    // non-leaf tuple arrives, its child tuples are already alive.
    // =====================================================================

    Path dir = Path.of(tpchDataDir);
    List<TupleUpdate> allUpdates = new ArrayList<>();

    System.out.println("Loading TPC-H data from: " + dir);
    loadTable(dir.resolve("nation.tbl"), allUpdates, "nation");
    loadTable(dir.resolve("customer.tbl"), allUpdates, "customer");
    loadTable(dir.resolve("orders.tbl"), allUpdates, "orders");
    loadTable(dir.resolve("lineitem.tbl"), allUpdates, "lineitem");
    System.out.printf("Loaded %d update records.%n", allUpdates.size());

    // Also load incremental update files if present (from dbgen -U)
    for (int i = 1; ; i++) {
      Path lineitemUpdate = dir.resolve("lineitem.tbl.u" + i);
      Path ordersUpdate = dir.resolve("orders.tbl.u" + i);
      if (!Files.exists(lineitemUpdate) && !Files.exists(ordersUpdate)) break;
      if (Files.exists(ordersUpdate)) {
        loadUpdateFile(ordersUpdate, allUpdates, "orders");
      }
      if (Files.exists(lineitemUpdate)) {
        loadUpdateFile(lineitemUpdate, allUpdates, "lineitem");
      }
    }

    // =====================================================================
    // Source: from pre-loaded collection
    // =====================================================================

    DataStream<TupleUpdate> updates =
        env.fromCollection(allUpdates, TypeInformation.of(TupleUpdate.class))
            .name("tpch-update-source");

    // =====================================================================
    // Core AJU: incrementally maintain the 4-way foreign-key acyclic join
    // =====================================================================

    DataStream<JoinResult> joinDeltas =
        updates.process(new Q10ProcessFunction()).name("aju-q10-join");

    // =====================================================================
    // Aggregation: incremental SUM(revenue) grouped by customer
    // =====================================================================

    DataStream<Q10Aggregator.AggregateResult> aggregated =
        joinDeltas.process(new Q10Aggregator()).name("q10-aggregator");

    // =====================================================================
    // Top-K: maintain top 20 by revenue descending
    // =====================================================================

    DataStream<Q10Aggregator.AggregateResult> topK =
        aggregated.process(new TopKMaintainer()).name("top-k-maintainer");

    // =====================================================================
    // Sink: output results
    // =====================================================================

    topK.addSink(new DeltaSink()).name("delta-sink");

    env.execute("AJU Q10");
  }

  // =========================================================================
  // File loading utilities
  // =========================================================================

  private static void loadTable(Path file, List<TupleUpdate> updates, String relation)
      throws Exception {
    if (!Files.exists(file)) return;
    try (BufferedReader reader = Files.newBufferedReader(file)) {
      String line;
      while ((line = reader.readLine()) != null) {
        if (line.isBlank()) continue;
        TupleUpdate update = parseLine(line, relation, UpdateType.INSERT);
        if (update != null) updates.add(update);
      }
    }
  }

  private static void loadUpdateFile(Path file, List<TupleUpdate> updates, String relation)
      throws Exception {
    if (!Files.exists(file)) return;
    try (BufferedReader reader = Files.newBufferedReader(file)) {
      String line;
      boolean isDelete = true;
      while ((line = reader.readLine()) != null) {
        if (line.isBlank()) continue;
        UpdateType type = isDelete ? UpdateType.DELETE : UpdateType.INSERT;
        TupleUpdate update = parseLine(line, relation, type);
        if (update != null) updates.add(update);
        isDelete = !isDelete;
      }
    }
  }

  private static TupleUpdate parseLine(String line, String relation, UpdateType type) {
    return switch (relation) {
      case "nation" -> new NationUpdate(type, TpchCsvParser.parseNation(line));
      case "customer" -> new CustomerUpdate(type, TpchCsvParser.parseCustomer(line));
      case "orders" -> new OrdersUpdate(type, TpchCsvParser.parseOrders(line));
      case "lineitem" -> new LineitemUpdate(type, TpchCsvParser.parseLineitem(line));
      default -> null;
    };
  }
}
