package hk.ust;

import hk.ust.aggregate.Q10Aggregator;
import hk.ust.aggregate.Q10UnifiedBatchFunction;
import hk.ust.metrics.Phase;
import hk.ust.metrics.RunMetrics;
import hk.ust.model.TupleUpdate;
import hk.ust.source.TpchUpdateCounter;
import hk.ust.source.TpchUpdateSource;
import org.apache.flink.api.common.JobExecutionResult;
import org.apache.flink.api.common.typeinfo.TypeInformation;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.streaming.api.functions.sink.legacy.DiscardingSink;
import java.nio.file.Path;

/**
 * AJU (Acyclic Join under Updates) streaming job for TPC-H Q10.
 *
 * <p>Pipeline: {@link TpchUpdateSource} -> {@link Q10UnifiedBatchFunction} (AJU + batch aggregate +
 * top-K in one operator, matching standalone finalization).
 */
public class AjuStreamJob {

  public static void main(String[] args) throws Exception {
    String tpchDataDir = System.getenv("TPCH_DATA_DIR");
    if (tpchDataDir == null || tpchDataDir.trim().isEmpty()) {
      throw new IllegalStateException(
          "TPCH_DATA_DIR environment variable is not set. "
              + "Point it to the directory containing .tbl files generated by dbgen.");
    }

    try (RunMetrics metrics = RunMetrics.start("flink", tpchDataDir)) {
      StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
      env.setParallelism(1);

      Path dir = Path.of(tpchDataDir);

      long updatesTotal;
      try (var loadPhase = metrics.phase(Phase.LOAD)) {
        System.out.println("Counting TPC-H updates in: " + dir);
        updatesTotal = TpchUpdateCounter.count(dir);
        System.out.printf("Will process %d update records.%n", updatesTotal);
      }

      metrics.setUpdatesTotal(updatesTotal);
      metrics.setPreloadUpdatesCount(0);

      DataStream<TupleUpdate> updates =
          env.addSource(new TpchUpdateSource(tpchDataDir), "tpch-update-source")
              .returns(TypeInformation.of(TupleUpdate.class));

      updates
          .process(new Q10UnifiedBatchFunction())
          .name("aju-q10-unified-batch")
          .addSink(new DiscardingSink<Q10Aggregator.AggregateResult>())
          .name("discarding-sink");

      JobExecutionResult result;
      try (var pipelinePhase = metrics.phase(Phase.AJU)) {
        result = env.execute("AJU Q10");
      }

      if (result != null) {
        System.out.printf("Flink job finished in %d ms.%n", result.getNetRuntime());
      }
    }
  }
}
