package hk.ust;

import hk.ust.metrics.FlinkBreakdownReporter;
import hk.ust.metrics.FlinkOperatorTimings;
import hk.ust.metrics.RunMetrics;
import hk.ust.source.TpchUpdateCounter;
import java.nio.file.Path;
import org.apache.flink.api.common.JobExecutionResult;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;

/**
 * AJU (Acyclic Join under Updates) streaming job for TPC-H Q10.
 *
 * <p>Supports three pipeline modes via {@code CQUIRREL_PIPELINE}:
 *
 * <ul>
 *   <li>{@code unified} — single fused operator (default)
 *   <li>{@code split} — AJU then parallel aggregation + global top-K
 *   <li>{@code partitioned} — customer-subtree partitioned AJU + parallel aggregation
 * </ul>
 */
public class AjuStreamJob {

  public static void main(String[] args) throws Exception {
    String tpchDataDir = System.getenv("TPCH_DATA_DIR");
    if (tpchDataDir == null || tpchDataDir.trim().isEmpty()) {
      throw new IllegalStateException(
          "TPCH_DATA_DIR environment variable is not set. "
              + "Point it to the directory containing .tbl files generated by dbgen.");
    }

    String outputPath = System.getProperty("q10.output", "result/flink-q10.csv");

    try (RunMetrics metrics = RunMetrics.start("flink", tpchDataDir)) {
      StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

      Path dir = Path.of(tpchDataDir);

      long updatesTotal;
      System.out.println("Counting TPC-H updates in: " + dir);
      updatesTotal = TpchUpdateCounter.count(dir);
      System.out.printf("Will process %d update records.%n", updatesTotal);

      metrics.setUpdatesTotal(updatesTotal);
      metrics.setPreloadUpdatesCount(0);

      AjuPipelineBuilder.wire(env, tpchDataDir, metrics, outputPath);

      FlinkOperatorTimings.reset();

      long executeStartNs = System.nanoTime();
      JobExecutionResult result = env.execute("AJU Q10");
      long executeWallNs = System.nanoTime() - executeStartNs;

      FlinkOperatorTimings.recordClusterOverhead(executeWallNs);
      FlinkOperatorTimings.flushTo(metrics);
      FlinkOperatorTimings.flushClusterTo(metrics);

      long executeWallMs = executeWallNs / 1_000_000L;
      FlinkBreakdownReporter.print(executeWallMs, metrics.phasesMsSnapshot());

      if (result != null) {
        System.out.printf(
            "Flink job finished in %d ms (JobExecutionResult.getNetRuntime).%n",
            result.getNetRuntime());
      }
    }
  }
}
