package hk.ust.source;

import hk.ust.metrics.FlinkOperatorTimings;
import hk.ust.metrics.Phase;
import hk.ust.model.*;
import hk.ust.model.TupleUpdate.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.apache.flink.streaming.api.functions.source.legacy.RichSourceFunction;

/**
 * Flink source that reads TPC-H .tbl files and emits them as a stream of updates.
 *
 * <p>Phase 1 (bulk load): Reads all 4 tables in bottom-up order (nation, customer, orders,
 * lineitem) and emits each row as an INSERT. Bottom-up ordering ensures that when a non-leaf tuple
 * arrives, its child tuples are already alive, avoiding unnecessary accumulation in N(R).
 *
 * <p>Phase 2 (incremental updates): Reads update files (*.tbl.u1, etc.) generated by dbgen -U, if
 * present. These contain DELETE/INSERT pairs.
 */
public class TpchUpdateSource extends RichSourceFunction<TupleUpdate> {

  private final String dataDir;
  private volatile boolean running = true;

  public TpchUpdateSource(String dataDir) {
    this.dataDir = dataDir;
  }

  @Override
  public void run(SourceContext<TupleUpdate> ctx) throws Exception {
    Path dir = Path.of(dataDir);

    // Phase 1: Bulk load in bottom-up order (leaf to root).
    // This ensures children are alive before parents arrive.
    loadTable(dir.resolve("nation.tbl"), ctx, "nation");
    loadTable(dir.resolve("customer.tbl"), ctx, "customer");
    loadTable(dir.resolve("orders.tbl"), ctx, "orders");
    loadTable(dir.resolve("lineitem.tbl"), ctx, "lineitem");

    // Phase 2: Process update files if they exist.
    // dbgen -U generates files like lineitem.tbl.u1, orders.tbl.u1, etc.
    // Each update file contains pairs: first a DELETE tuple, then an INSERT tuple.
    for (int i = 1; running; i++) {
      Path lineitemUpdate = dir.resolve("lineitem.tbl.u" + i);
      Path ordersUpdate = dir.resolve("orders.tbl.u" + i);
      if (!Files.exists(lineitemUpdate) && !Files.exists(ordersUpdate)) {
        break;
      }
      if (Files.exists(ordersUpdate)) {
        loadUpdateFile(ordersUpdate, ctx, "orders");
      }
      if (Files.exists(lineitemUpdate)) {
        loadUpdateFile(lineitemUpdate, ctx, "lineitem");
      }
    }
  }

  private void loadTable(Path file, SourceContext<TupleUpdate> ctx, String relation)
      throws IOException {
    if (!Files.exists(file)) return;
    try (BufferedReader reader = Files.newBufferedReader(file)) {
      String line;
      while (running && (line = readTimedLine(reader)) != null) {
        if (line.isBlank()) continue;
        parseAndCollect(line, relation, UpdateType.INSERT, ctx);
      }
    }
  }

  /**
   * dbgen update files alternate DELETE and INSERT lines for each update pair. Lines are in the
   * standard pipe-delimited format.
   */
  private void loadUpdateFile(Path file, SourceContext<TupleUpdate> ctx, String relation)
      throws IOException {
    if (!Files.exists(file)) return;
    try (BufferedReader reader = Files.newBufferedReader(file)) {
      String line;
      boolean isDelete = true; // First line of each pair is a DELETE
      while (running && (line = readTimedLine(reader)) != null) {
        if (line.isBlank()) continue;
        UpdateType type = isDelete ? UpdateType.DELETE : UpdateType.INSERT;
        parseAndCollect(line, relation, type, ctx);
        isDelete = !isDelete;
      }
    }
  }

  private String readTimedLine(BufferedReader reader) throws IOException {
    long t0 = System.nanoTime();
    String line = reader.readLine();
    FlinkOperatorTimings.add(Phase.LOAD, System.nanoTime() - t0);
    return line;
  }

  private TupleUpdate parseAndCollect(
      String line, String relation, UpdateType type, SourceContext<TupleUpdate> ctx) {
    long t0 = System.nanoTime();
    TupleUpdate update = parseLine(line, relation, type);
    FlinkOperatorTimings.add(Phase.LOAD, System.nanoTime() - t0);
    if (update != null) {
      t0 = System.nanoTime();
      ctx.collect(update);
      FlinkOperatorTimings.add(Phase.RUNTIME, System.nanoTime() - t0);
    }
    return update;
  }

  private TupleUpdate parseLine(String line, String relation, UpdateType type) {
    return switch (relation) {
      case "nation" -> new NationUpdate(type, TpchCsvParser.parseNation(line));
      case "customer" -> new CustomerUpdate(type, TpchCsvParser.parseCustomer(line));
      case "orders" -> new OrdersUpdate(type, TpchCsvParser.parseOrders(line));
      case "lineitem" -> new LineitemUpdate(type, TpchCsvParser.parseLineitem(line));
      default -> null;
    };
  }

  @Override
  public void cancel() {
    running = false;
  }
}
